[IDE]
# ZuluIDE ini file for Roland SP-808

max_udma = -1             # -1 to disable UDMA
max_pio = 3               # Maximum PIO mode to use
max_blocksize = 512       # Maximum number of bytes per transfer block for SP-808
device = Zip100
atapi_vendor = "IOMEGA"
atapi_product = "ZIP 100"
atapi_version = "N.38"
